### ISSUE TITLE
No joy on unified

### ISSUE THREAD

**Issue by JoeCooper** [jamesmontemagno/Mvx.Plugins.Settings#15]
I've installed 1402 which, in the description on NuGet, says it's good for unified.

But at runtime, Mvx.GetSingleton<ISettings> fails to resolve.

The bootstrap, which refers to Refractored.MvxPlugins.Settings.Touch.Plugin, is unbuildable as the namespace .Touch does not exist.

I checked the references and found that while the portable DLL is referenced, nothing else is. I looked in the packages directory to see if I could manually add the appropriate DLL from the lib folder, but I only found the following platforms:

– monoandroid
– monotouch
– portable-net45+wp8+wpa81+win8+monoandroid+monotouch
– win8
– wp8
– wpa81

I examined the .nupkg file (cat | strings | grep) and didn't find anything else.

What's going down?

**Comment by jamesmontemagno** [comment]
Have you removed the nuget completely and re-added it?

**Comment by jamesmontemagno** [comment]
Oh yes you are correct it does not support unified yet. I will update to 1.5.0.0 soon.

**Comment by jamesmontemagno** [comment]
Here you go I have pushed out an update https://www.nuget.org/packages/Mvx.Plugins.Settings/
