### ISSUE TITLE
SettingsPluginBoostrap build error

### ISSUE THREAD

**Issue by JoeCooper** [jamesmontemagno/Mvx.Plugins.Settings#16]
Version 1403 installs with a file, Bootstrap/SettingsPluginBoostrap.cs, which fails to compile due to an error:

/Users/joecooper/Projects/[redacted]/Bootstrap/SettingsPluginBootstrap.cs(62,62): Error CS0234: The type or namespace name `PluginLoader' does not exist in the namespace `Refractored.MvxPlugins.Settings'. Are you missing an assembly reference? (CS0234) ([redacted])

**Comment by jamesmontemagno** [comment]
Is there a namespace that needs to be added to fix this up?

**Comment by JoeCooper** [comment]
I tried doing so but it doesn't seem to exist. I wound up copying the missing class into the bootstrap from the sources on git hub. It builds and runs and works now on mine but you might want to check this on a clean installation or something.

– Joe

**Comment by ievgen** [comment]
Hey guys, I got the same error just now after migrating my Xamarin project to Unified API and updating Mvx.Plugin.Settings from NuGet. 

It seems that NuGet Package libs for "Xamarin.iOS10" is missing library Refractored.MvxPlugins.Settings.dll, this is why the project isn't compiled with error:

SettingsPluginBootstrap.cs(62,62): Error CS0234: The type or namespace name `PluginLoader' does not exist in the namespace `Refractored.MvxPlugins.Settings'. Are you missing an assembly reference? (CS0234)

**Comment by jamesmontemagno** [comment]
I just pushed 1.4.1 with a fix.

Sorry about that.
