### ISSUE TITLE
Failed to resolve type Refractored.MvxPlugins.Settings.ISettings

### ISSUE THREAD

**Issue by Uddhao** [jamesmontemagno/Mvx.Plugins.Settings#18]
After upgrade MvvmCross 4 above error occurred for WP but it is working fine in Droid. Setting class  not changed in MvvmCross 4 but exception occur while getting singleton of ISetting.

**Comment by jamesmontemagno** [comment]
This package is obsolete, please use: https://www.nuget.org/packages/Xam.Plugins.Settings
