### ISSUE TITLE
Something is broken when using Azure Mobile Services

### ISSUE THREAD

**Issue by dsancho** [jamesmontemagno/Mvx.Plugins.Settings#6]
After creating the MobileServiceClient in Android then the settings stop working when reading values.

The exception throwed is 'System.ArgumentException: 'jobject' must not be IntPtr.Zero.'

I have done several tests and always is the same, just create the MobileServiceClient and Settings stop working.

**Comment by gatm50** [comment]
Hi James I have the same problem. 
To reproduce the issue only you need to add this line to your App.cs in your Core.dll

        // This MobileServiceClient has been configured to communicate with your Mobile Service's url
        // and application key. You're all set to start working with your Mobile Service!
        public static MobileServiceClient MobileService = new MobileServiceClient(
             "https://somedomain.azure-mobile.net/",
             "somekey"
        );

**Comment by jamesmontemagno** [comment]
is the "somekey" coming from the Settings library? 

What build issue are you getting?

**Comment by gatm50** [comment]
"somekey" is a random string, I got it from the Azure site. I'm using the last version from Nuget of your plugin and of the Azure Mobile Service SDK
 
As a simple workaround, I edited the method "GetValueOrDefault" like this:

public T GetValueOrDefault<T>(string key, T defaultValue = default(T))
        {
            lock (locker)
            {
                //https://github.com/jamesmontemagno/Mvx.Plugins.Settings/issues/6
                var temporalPref = PreferenceManager.GetDefaultSharedPreferences(Application.Context);
                Type typeOf = typeof(T);
                if (typeOf.IsGenericType && typeOf.GetGenericTypeDefinition() == typeof(Nullable<>))
                {
                    typeOf = Nullable.GetUnderlyingType(typeOf);
                }

                object value = null;
                var typeCode = Type.GetTypeCode(typeOf);
                switch (typeCode)
                {
                    case TypeCode.Decimal:
                        value = (decimal)temporalPref.GetLong(key, (long)Convert.ToDecimal(defaultValue, System.Globalization.CultureInfo.InvariantCulture));
                        break;
                    case TypeCode.Boolean:
                        value = temporalPref.GetBoolean(key, Convert.ToBoolean(defaultValue));
                        break;
                    case TypeCode.Int64:
                        value = (Int64)temporalPref.GetLong(key, (long)Convert.ToInt64(defaultValue, System.Globalization.CultureInfo.InvariantCulture));
                        break;
                    case TypeCode.String:
                        value = temporalPref.GetString(key, Convert.ToString(defaultValue));
                        break;
                    case TypeCode.Double:
                        value = (double)temporalPref.GetLong(key, (long)Convert.ToDouble(defaultValue, System.Globalization.CultureInfo.InvariantCulture));
                        break;
                    case TypeCode.Int32:
                        value = temporalPref.GetInt(key, Convert.ToInt32(defaultValue, System.Globalization.CultureInfo.InvariantCulture));
                        break;
                    case TypeCode.Single:
                        value = temporalPref.GetFloat(key, Convert.ToSingle(defaultValue, System.Globalization.CultureInfo.InvariantCulture));
                        break;
                    case TypeCode.DateTime:
                        var ticks = temporalPref.GetLong(key, -1);
                        if (ticks == -1)
                            value = defaultValue;
                        else
                            value = new DateTime(ticks);
                        break;
                    default:

                        if (defaultValue is Guid)
                        {
                            var outGuid = Guid.Empty;
                            Guid.TryParse(temporalPref.GetString(key, Guid.Empty.ToString()), out outGuid);
                            value = outGuid;
                        }
                        else
                        {
                            throw new ArgumentException(string.Format("Value of type {0} is not supported.", value.GetType().Name));
                        }

                        break;
                }
                return null != value ? (T)value : defaultValue;
            }
        }

**Comment by jamesmontemagno** [comment]
I will take a look at it this week and see what the real root cause is. 

Thanks for the code sample. It has been hard to look into as there are not many reports and no one gave me a good repo at all or details.

**Comment by jamesmontemagno** [comment]
This package is obsolete, please use: https://www.nuget.org/packages/Xam.Plugins.Settings
